name: $(Date:yyyyMMdd).$(Rev:r)

variables:
  - name: Codeql.Enabled
    value: true
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
trigger: none
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      os: linux
      name: 1ES_JavaTooling_Pool
      image: 1ES_JavaTooling_Ubuntu-2004
    sdl:
      sourceAnalysisPool:
        name: 1ES_JavaTooling_Pool
        image: 1ES_JavaTooling_Windows_2022
        os: windows
    stages:
      - stage: Build
        jobs:
          - job: Build
            displayName: Eclipse-Copilot-Build
            templateContext:
              outputs:
                - output: pipelineArtifact
                  artifactName: output
                  targetPath: '$(Build.ArtifactStagingDirectory)/output'
                  displayName: "Publish Artifact: output"
            steps:
              - checkout: self
                fetchTags: false

              - task: JavaToolInstaller@0
                displayName: Use Java 17
                inputs:
                  versionSpec: "17"
                  jdkArchitectureOption: x64
                  jdkSourceOption: PreInstalled

              - task: UseNode@1
                displayName: Use Node 20.x
                inputs:
                  version: '20.x'

              - bash: npm i
                workingDirectory: org.eclipse.copilot.core/copilot-agent
                displayName: Install Copilot LS

              - bash: ./mvnw clean package
                displayName: 'Run Maven Clean and Package'

              - task: CopyFiles@2
                displayName: Copy output
                inputs:
                  Contents: |
                    org.eclipse.copilot.repository/target/repository
                    org.eclipse.copilot.repository/target/org.eclipse.copilot.repository-*.zip
                  TargetFolder: '$(Build.ArtifactStagingDirectory)/output'